### ISSUE TITLE
Bug: upon creating subaccount the "receive" tab has an undefined permanent payment url until next login

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/GreenAddressWebFiles#103]
tested 2of3 w/ Nano S but possible the type of subaccount and using a hardware wallet don't make a difference.

logout, login fixes it (for that newly created subaccount)

**Comment by gwillen** [comment]
I'm the original reporter of this bug -- when I got it, it was with a 2of2 with a Nano S, same problem (same fix).

**Comment by greenaddress** [comment]
fixed

**Comment by fiubit** [comment]
[https://0101bit.tumblr.com/post/138848948734/claim-9000-satoshi-every-60-minutes](url)
