### ISSUE TITLE
CAD exchange rate

### ISSUE THREAD

**Issue by findkiko** [greenaddress/GreenAddressWebFiles#4]
This could be determined to be user error but thought I should point out the UX inconsistency.

* App was set to fetch price from Cavirtex (now likely deprecated API from Kraken purchase/migration).
* App displays outdated price (at +$100 of current spot!) but UI says it checked 1min ago.

I'm not sure what codes/prices Cavirtex api's are currently returning, but this caused some hassle as an additional confirmation is needed to top up the payment.

_Side note: QuadrigaCX would be a good Canadian addition to the price menu._

Thanks.

**Comment by greenaddress** [comment]
fixed and added QuadrigaCX
