### ISSUE TITLE
Issues receiving short messages

### ISSUE THREAD

**Issue by yepub** [greenaddress/GreenAddressWebFiles#55]
Hey guys, nomerous reports of not receiving confirmation sms codes in Ukraine (Lifecell). Please take care ASAP. Thanks

**Comment by greenaddress** [comment]
Hello,

Thanks for the report. Apologies, indeed our SMS provider often seems to have issues with Ukraine, they usually address that quickly but it keeps happening (updated routing). We can process things manually if coordinated with our support team to enable Google Authenticator or other two factor authentication to avoid this issue in the short term. 

In the long term we are planning to deprecate (but keep for current users) SMS as it is less secure than other options (and plan to add U2F)

Regards

**Comment by yepub** [comment]
Thanks guys, so you can enable Google Authenticator for me? What should I do?

**Comment by greenaddress** [comment]
We need to arrange a synchronized private chat (via our email support) where you enable any other 2FA via the wallet as per normal and we send you the sms manually from a different service and we need to synchronize as those sms are only valid for 5 minutes.

**Comment by yepub** [comment]
Everything is working now, sms was delivered and I just added Google 2FA, thank you :)

**Comment by greenaddress** [comment]
you're welcome! glad it's fine now.

For any future reader, please enable multiple 2FA in advance as SMS can be pretty unreliable sometimes and not as secure as other options (SMS has been found to be quite weak in studies)
