### ISSUE TITLE
Issues receiving sms Ukraine

### ISSUE THREAD

**Issue by Filin4eg-Sergey** [greenaddress/GreenAddressWebFiles#65]
Hello, I have a problem with 2FA, can`t receive sms request limit exceeded always. And can`t disabled it.
Number Kyivstar: +38067, +38096, +38097, +38098, +38068
can you please help me?
My money is frozen on the wallet

**Comment by pptp** [comment]
The same problem in Russia

**Comment by jgriffiths** [comment]
Hi,

Please contact info@greenaddress.it for issues relating to SMS 2fa and include the phone number as it is shown in your wallet settings.
