### ISSUE TITLE
Authentication by call and SMS not working in Hungary

### ISSUE THREAD

**Issue by herbat** [greenaddress/GreenAddressWebFiles#66]
I tested it with different phones and different wallets and the call and SMS 2FA-s are not working in Hungary right now. Both worked a few days ago but not now. Greenbits app gives the 'Internal error' message.

**Comment by herbat** [comment]
This should probably be merged with issue No. 65.

**Comment by jgriffiths** [comment]
Hi,

Please contact info@greenaddress.it for issues relating to SMS 2fa and include the phone number as it is shown in your wallet settings.
